### PR TITLE
Kill dead file?

### PR DESCRIPTION
**Pull request by alex-ozdemir**
I think that this is dead.

### CODE REVIEW

**Comment by edwjchen** [comment]
@alex-ozdemir On a related note, the third_party/EzPC directory isn't necessary anymore too. Do you mind if I add the changes to this PR?

**Comment by alex-ozdemir** [comment]
Go for it!

**Review by kwantam — APPROVED** [review]
sorry, I'm sure this is my fault.

**Comment by alex-ozdemir** [comment]
I just went ahead and merged--I assume creating a new PR isn't too hard, Edward.

**Comment by edwjchen** [comment]
> I just went ahead and merged--I assume creating a new PR isn't too hard, Edward.

Yep sorry for the delays, made the PR now!

**Comment by alex-ozdemir** [comment]
No worries at all :slightly_smiling_face:

**Pull request merged**
