### PR TITLE
Introducing SV Comp-style tests for C Frontend

### PR DESCRIPTION
**Pull request by edwjchen**
- Added COpt to Circ options
- Cherrypicked https://github.com/circify/circ/pull/100 
- renaming C primitive terms (e.g. CInt --> Int) 
- Added AND case in cfold pass

### CODE REVIEW

**Comment by alex-ozdemir** [comment]
Can you say a bit about why you changed AND cfolding? And why you didn't change OR?

**Comment by alex-ozdemir** [comment]
Also, does your AND optimization take time quadratic in the number of arguments?

**Comment by edwjchen** [comment]
> Can you say a bit about why you changed AND cfolding? And why you didn't change OR?
Added a similar OR optimization

>  Also, does your AND optimization take time quadratic in the number of arguments?
Updated to run in linear time!

**Review by alex-ozdemir — APPROVED** [review]
(pending CI fix)

**Pull request merged**
